$Key = @();
$Value = @();
$dataRow = @();
$Body;
$startDate = Get-Date;

##### Loop through the data File
Function InvokeWebRequest($dataFile) {
    foreach ($row in $dataFile){
        foreach($property in $row.psobject.Properties){
            $Key = ($property | Select-Object -Property name | % {$_.Name})
            $Value = ($property | Select-Object -Property value | % {$_.Value})
            if([string]$Value -as [DateTime]){
                #$Value = Get-Date $Value -Format 'MfM/dd/yyyy'
                $Value = Get-Date $Value -Format 'MM/dd/yyyy'
            }

            $Body += [string]([string]$Key + "=" + [string]$Value + "&")
        }
        $dataRow +=$Body
    }
    $arr = $Body -split '&environment'
    for($i=1; $i -lt $arr.Count; $i++){
        $arr[$i] = "environment" + $arr[$i]
    }
    for($loop=0; $loop -lt $arr.count; $loop++){
        $Response = Invoke-WebRequest -Uri "http://bltmlu1:8080/testbillingui/services" -Method POST -Body $arr[$loop] 
        Write-Output $Response.Content
    }
}

#### This executes the aging tool, I should know when the batch file is done executing.
Function executeAging($date){
    powershell.exe D:\Tools\shelter-batch-tool\shelter-batch-tool-unit.bat $date -Wait -NoNewWindow | Out-Host
}

#### This gets the next file to process
Function getDataFile(){
    return 1
}

# Age this until Day 63
executeAging(Get-Date $startDate.AddDays(62) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 63 - Refund Set up.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 63 - Refund Set up.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 63"

# Age this until Day 65
executeAging(Get-Date $startDate.AddDays(64) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 65 - PC CAN.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 65 - PC CAN.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 65"

# Age this until Day 67
executeAging(Get-Date $startDate.AddDays(66) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 67 - PC for refund.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 67 - PC for refund.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 67"

# Age this until Day 75
executeAging(Get-Date $startDate.AddDays(74) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 75 - PC PAY.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 75 - PC PAY.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 75"


# Age this until Day 85
executeAging(Get-Date $startDate.AddDays(84) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 85 - Pay.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 85 - Pay.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 85"


# Age this until Day 145
executeAging(Get-Date $startDate.AddDays(144) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 145 - PC.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 145 - PC.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 145"


# Age this until Day 146
executeAging(Get-Date $startDate.AddDays(145) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 146 - CAN.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 146 - CAN.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 146"

# Age this until Day 148
executeAging(Get-Date $startDate.AddDays(147) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 148 - Renewal Offer.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 148 - Renewal Offer.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 148"

# Age this until Day 151
executeAging(Get-Date $startDate.AddDays(150) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 151 - PC CAN.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 151 - PC CAN.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 151"