$Key = @();
$Value = @();
$dataRow = @();
$Body;
$startDate = Get-Date;

##### Loop through the data File
Function InvokeWebRequest($dataFile) {
    foreach ($row in $dataFile){
        foreach($property in $row.psobject.Properties){
            $Key = ($property | Select-Object -Property name | % {$_.Name})
            $Value = ($property | Select-Object -Property value | % {$_.Value})
            if([string]$Value -as [DateTime]){
                #$Value = Get-Date $Value -Format 'MfM/dd/yyyy'
                $Value = Get-Date $Value -Format 'MM/dd/yyyy'
            }

            $Body += [string]([string]$Key + "=" + [string]$Value + "&")
        }
        $dataRow +=$Body
    }
    $arr = $Body -split '&environment'
    for($i=1; $i -lt $arr.Count; $i++){
        $arr[$i] = "environment" + $arr[$i]
    }
    for($loop=0; $loop -lt $arr.count; $loop++){
        $Response = Invoke-WebRequest -Uri "http://bltmlu1:8080/testbillingui/services" -Method POST -Body $arr[$loop] 
        Write-Output $Response.Content
    }
}

#### This executes the aging tool, I should know when the batch file is done executing.
Function executeAging($date){
    powershell.exe D:\Tools\shelter-batch-tool\shelter-batch-tool-unit.bat $date -Wait -NoNewWindow | Out-Host
}

#### This gets the next file to process
Function getDataFile(){
    return 1
}

# Age this until Day 12
# executeAging(Get-Date $startDate.AddDays(11) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 12 - reinstatement.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 12 - reinstatement.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 12"

# Age this until Day 20
executeAging(Get-Date $startDate.AddDays(19) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 20 - Step 1 - PC Can Rein.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 20 - Step 1 - PC Can Rein.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 20 - Step 1"

# Run Day 20 - Step 2
write-output "`n Regression - Say - Day 20 - step 2 - PC REIN.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 20 - Step 2 - Pay.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 20 - Step 2"

# Age it until day 22
executeAging(Get-Date $startDate.AddDays(21) -Format 'yyyy-MM-dd')
write-output "`n Regression - Say - Day 22 - PC CAN.xlsx"
$dataFile = Import-Excel ("D:\RegressionTests_New\Test Data - R12 - UNIT - Say Regression - 2019 08 02-template-for-autogenerated-data\Regression - Say - Day 22 - PC CAN.xlsx")
InvokeWebRequest($dataFile)
Write-Output "`n Finished Day 22"